Add files via upload
Below i have copied and pasted an error that i am getting when i try to compile the geant4 code. The error is due to changes i made trying to include the Particle Momentum Direction. I think this is due to the  G4ThreeVector IsotropicParticleDirection(); function and my declaration in the PrimaryGeneratorAction header file.

adi@adi-Lenovo-E51-80:~/GEANT4/geant4_work/examples/B4a-buildmod$ make -j4
/usr/local/bin/cmake -S/home/adi/GEANT4/geant4_work/examples/B4amod -B/home/adi/GEANT4/geant4_work/examples/B4a-buildmod --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/bin/cmake -E cmake_progress_start /home/adi/GEANT4/geant4_work/examples/B4a-buildmod/CMakeFiles /home/adi/GEANT4/geant4_work/examples/B4a-buildmod//CMakeFiles/progress.marks
make -s -f CMakeFiles/Makefile2 all
Scanning dependencies of target exampleB4a
[ 12%] Building CXX object CMakeFiles/exampleB4a.dir/src/B4PrimaryGeneratorAction.cc.o
[ 25%] Building CXX object CMakeFiles/exampleB4a.dir/src/B4aActionInitialization.cc.o
In file included from /home/adi/GEANT4/geant4_work/examples/B4amod/src/B4aActionInitialization.cc:31:0:
/home/adi/GEANT4/geant4_work/examples/B4amod/include/B4PrimaryGeneratorAction.hh:52:3: error: ‘G4ThreeVector’ does not name a type
   G4ThreeVector IsotropicParticleDirection();    
   ^
In file included from /home/adi/GEANT4/geant4_work/examples/B4amod/src/B4PrimaryGeneratorAction.cc:30:0:
/home/adi/GEANT4/geant4_work/examples/B4amod/include/B4PrimaryGeneratorAction.hh:52:3: error: ‘G4ThreeVector’ does not name a type
   G4ThreeVector IsotropicParticleDirection();    
   ^
CMakeFiles/exampleB4a.dir/build.make:134: recipe for target 'CMakeFiles/exampleB4a.dir/src/B4aActionInitialization.cc.o' failed
make[2]: *** [CMakeFiles/exampleB4a.dir/src/B4aActionInitialization.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/adi/GEANT4/geant4_work/examples/B4amod/src/B4PrimaryGeneratorAction.cc:46:15: error: ‘PrimaryGeneratorAction’ has not been declared
 G4ThreeVector PrimaryGeneratorAction::IsotropicParticleDirection()
               ^
CMakeFiles/exampleB4a.dir/build.make:108: recipe for target 'CMakeFiles/exampleB4a.dir/src/B4PrimaryGeneratorAction.cc.o' failed
make[2]: *** [CMakeFiles/exampleB4a.dir/src/B4PrimaryGeneratorAction.cc.o] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/exampleB4a.dir/all' failed
make[1]: *** [CMakeFiles/exampleB4a.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
adi@adi-Lenovo-E51-80:~/GEANT4/geant4_work/examples/B4a-buildmod$ ^C
adi@adi-Lenovo-E51-80:~/GEANT4/geant4_work/examples/B4a-buildmod$